### ISSUE TITLE
Make a topics page with all the available Quote tags

### ISSUE THREAD

**Issue by Abhijeet-2003** [boradesanket13/QuoteBuzz#101]

**Comment by Abhijeet-2003** [comment]
Please assign @boradesanket13 .

**Comment by boradesanket13** [comment]
Sure! Go ahead. Awarding 3 points for creating this issue. Will give 20 for completing it as a hard issue @Abhijeet-2003

**Comment by Abhijeet-2003** [comment]
i've sent a pr. Kindly review and merge @boradesanket13.
