### ISSUE TITLE
Add better colors to buttons

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#65]
Feel free to discuss your ideas before asking to be asssigned

**Comment by inamdarketan** [comment]
I would like to contribute.

**Comment by Ajeetesh2003** [comment]
Hello, @boradesanket13 I would like to contribute to this issue.

**Comment by boradesanket13** [comment]
Go ahead! @Ajeetesh2003! Discuss your ideas before starting the work!

**Comment by Ajeetesh2003** [comment]
@boradesanket13  I have applied some color themes to the buttons as visible in the attached screenshot. Also,
![QuteBuzz-Buttons](https://user-images.githubusercontent.com/95238154/205495818-2df5cd71-3c14-412c-858e-1377c6753af4.png)
I have resized the buttons to have almost equal dimensions. Please view it once and suggest if something else has to be done.

**Comment by Ajeetesh2003** [comment]
Ok, I will apply these changes and update you soon.

**Comment by Ajeetesh2003** [comment]
@boradesanket13 , I have done some changes( refer to below video). Please review it and suggest if changes are needed to be done.

https://user-images.githubusercontent.com/95238154/205930353-720ea6c3-d896-47a6-9bf8-0446d7cca31a.mp4

**Comment by boradesanket13** [comment]
- Use more lighter shades of same color
- Yellow color is changing to orange on hover. Change it to dark yellow.
@Ajeetesh2003

**Comment by Ajeetesh2003** [comment]
I have applied the required changes as you advised. Please review it and share your feedback.

https://user-images.githubusercontent.com/95238154/206416528-978d3a5e-d173-434e-a109-f14012c674ef.mp4
