### ISSUE TITLE
Add LEARN. md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#68]
A LEARN.md file to provide step by step instructions, with text and/or media, on how to built this project from scratch.

**Comment by inamdarketan** [comment]
I would like to contribute.

**Comment by nik132-eng** [comment]
Can I enter if this problem hasn't been resolved? Can you provide me this issue?

**Comment by boradesanket13** [comment]
@nik132-eng Go for it
