### ISSUE TITLE
Increase transparency of the quote card 

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#70]
Increase transparency of the quote card so that image looks more visible

**Comment by boradesanket13** [comment]
https://www.figma.com/file/S5xcsUEPST9TKW3sPYkQy2/QuoteBuzz?node-id=0%3A1

**Comment by inamdarketan** [comment]
I would like to contribute.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀 @inamdarketan

**Comment by inamdarketan** [comment]
Thank you @boradesanket13 😃

**Comment by boradesanket13** [comment]
@inamdarketan GG!😁
