### ISSUE TITLE
Sort quotes by person feature

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#72]
🤖Elaborate how you will implement it to get assigned quickly. Be detailed!

- Add a drop down to choose names of great personalities
- After choosing the person display quotes of that person from an API

**Comment by AaryaaRam** [comment]
@boradesanket13 
I would like to work on this issue!!

**Comment by boradesanket13** [comment]
Discuss your idea here before starting to code! @AaryaaRam
