### ISSUE TITLE
Add 'quote of the day' 

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#73]
Add 'quote of the day' button in the navbar
- Redirect that button to a page, showing new quote each day.

**Comment by inamdarketan** [comment]
Please assign this task to me.

**Comment by Tushar98644** [comment]
I would like to take up the task...

**Comment by Abhijeet-2003** [comment]
Can I work on this @boradesanket13 ?

**Comment by boradesanket13** [comment]
@Tushar98644 is already assigned. Check other issues as of now @Abhijeet-2003
