### ISSUE TITLE
Create a navbar

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#74]
Create a navbar containing 
- Home page
- Authors page
- Topics page
-  Contact page

🤖Elaborate how you will implement it to get assigned quickly. Be detailed!

**Comment by shreyansh167** [comment]
@boradesanket13 I would like to work on this issue.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by Tushar98644** [comment]
I would also like to work on this issue ....

**Comment by boradesanket13** [comment]
@shreyansh167 
Go ahead! Contribute well🚀

**Comment by Abhijeet-2003** [comment]
@boradesanket13 I would like to work on this.

**Comment by Abhijeet-2003** [comment]
I've sent a pr for this issue @boradesanket13 . Please review and merge.
