### ISSUE TITLE
Create a contacts page

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#75]
Create a contacts page with logos:
- Twitter
- GitHub
- ProductHunt
- Email

**Comment by shivamkgpian** [comment]
i would like to this work

**Comment by Tushar98644** [comment]
i would to like to work on this issue...would be primarily using bootstrap for the same

**Comment by boradesanket13** [comment]
@shivamkgpian Go ahead!

**Comment by SattyamSamania** [comment]
@boradesanket13 can I work on this ?

**Comment by boradesanket13** [comment]
@SattyamSamania GO ahead
