### ISSUE TITLE
Create a contact form 

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#76]
Create a contact form on contact page.
- Name
- Email
- Message

🤖Elaborate how you will implement it to get assigned quickly. Be detailed! We encourage good discussion!

**Comment by shivamgupta2020** [comment]
I had already created a contact form. Screenshot is attached below.

**Screenshot**:-
![image](https://user-images.githubusercontent.com/91847638/205513634-4f66d45e-2455-4cfc-bd3b-f17f74c83abe.png)

Please assign this task to me.

**Comment by shivamkgpian** [comment]
hey @boradesanket13  can you please assign this to me

**Comment by shivamgupta2020** [comment]
@boradesanket13 please tell me if any changes should be made in above contact form?

**Comment by boradesanket13** [comment]
@shivamgupta2020  Add appropriate image on the left

**Comment by shivamgupta2020** [comment]
> @shivamgupta2020  Add appropriate image on the left

Please share image if u had any suggestion.

**Comment by boradesanket13** [comment]
Take favicon image from the codebase. 🌟
@shivamgupta2020

**Comment by Tushar98644** [comment]
@boradesanket13 if the issue still persists, kindly assign
