### ISSUE TITLE
Create a sign & sin up page UI

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#77]
- Create a sign & sin up page UI
- Add sign up button at top of home page

🤖Elaborate how you will implement it to get assigned quickly. Be detailed!  We encourage good discussion!

**Comment by Tushar98644** [comment]
The signup and login page UI can be easily made using tailwind/bootstrap ,as for the sign up and login in part do we need to set up a backend server or just do the design for the pages?

In any case, assign me this issue ....

**Comment by boradesanket13** [comment]
@shivamkgpian, thanks for your interest!

@, we're assigning issues on a first come first serve basis. If @Tushar98644  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by nik132-eng** [comment]
Can I enter if this problem hasn't been resolved? Can you provide me this issue?
