### ISSUE TITLE
Add your favourite (Saved) quotes page

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/QuoteBuzz#78]
Add your favourite (Saved) quotes page
- When user clicks to save the quote. It is saved in his profile under 'Saved quotes'

Discussions on this issue is highly encouraged before jumping into coding🚀⚒

**Comment by itz-deepak** [comment]
@boradesanket13 Please assign this to me

**Comment by boradesanket13** [comment]
@itz-deepak ✔

**Comment by itz-deepak** [comment]
Hello @boradesanket13 
How should I procced for this issue

**Comment by boradesanket13** [comment]
@itz-deepak Create a database to save the users favourite quotes in database. User should be able to see the saved quotes in the saved quote section in profile. 
Will assign 50 points for this issue.

**Comment by Abhijeet-2003** [comment]
Can I work on this ? @boradesanket13
