### ISSUE TITLE
Create a footer.

### ISSUE THREAD

**Issue by 1ananya3** [boradesanket13/QuoteBuzz#82]

**Comment by 1ananya3** [comment]
I want to work on this . Please assign it to me. @boradesanket13

**Comment by nik132-eng** [comment]
@boradesanket13 can I work on this issue?

**Comment by Jagroop2000** [comment]
Hi @boradesanket13 !!
Can I Work on this Issue ?

**Comment by boradesanket13** [comment]
@nik132-eng I have assigned you different issue on the same project. let's give this one to @Jagroop2000

**Comment by SattyamSamania** [comment]
Hey @boradesanket13 if the issue is still open can i work on this?
