### ISSUE TITLE
Add option to view all authors in one page 

### ISSUE THREAD

**Issue by Tushar98644** [boradesanket13/QuoteBuzz#90]

**Comment by Tushar98644** [comment]
kindly let me work on it @boradesanket13

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by boradesanket13** [comment]
Share your approach before starting to work

**Comment by Abhijeet-2003** [comment]
@boradesanket13 Can I work on this?

**Comment by Tushar98644** [comment]
> Share your approach before starting to work

wiil be using  api to fetch data of all the authors and display it using dom..
