### ISSUE TITLE
ADD google sign up option in sign up page ....

### ISSUE THREAD

**Issue by Tushar98644** [boradesanket13/QuoteBuzz#93]

**Comment by Tushar98644** [comment]
assign me @boradesanket13

**Comment by boradesanket13** [comment]
Ellaborate the changes that you make!

**Comment by Tushar98644** [comment]
will use google 0auth for this,....first wil  generate a client id and will set javascript authorized callback urls and redirect urls for verification and redirecting to main page....the google button can be created using a simple div class and the authentication is done using the generated client id...a call back funtion handles all the redirect endpoints ....
